### ISSUE TITLE
Importing and running with node gives error...

### ISSUE THREAD

**Issue by poetaman** [ansilove/ansilove.js#2]
Hi, I am trying to use this to get the json version of SAUCE record. In your README.md you provide the following recipe.

```
AnsiLove.sauce("example.ans", function (sauce) {
    console.log(sauce);
});
```

I tried to import ansilove.js in a short javascript file and ran it from command line to print SAUCE record, but it fails with following error:

```
/Users/poetaman/packages/ansilove.js/ansilove.js:2299
    if (!self.WorkerLocation) {
    ^

ReferenceError: self is not defined
    at /Users/poetaman/packages/ansilove.js/ansilove.js:2299:5
    at Object.<anonymous> (/Users/poetaman/packages/ansilove.js/ansilove.js:2514:2)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/poetaman/packages/ansilove.js/getsauce.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)

Node.js v19.2.0
```

Could you add a more complete example on how to use ansilove.js from terminal? Thanks!

**Comment by fcambus** [comment]
Thanks for the report.

ansilove.js is intended for use in a web browser, and I don't plan to support Node.js. I've removed the misleading main entry from package.json.
